version: "3.7"
services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: ripley-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    networks:
      - reanimated

networks:
  reanimated:
    driver: bridge
