@api = http://localhost:4000/api/v1/transfer

### INDEX
GET {{api}}/
Content-Type: application/json

### CREATE
GET {{api}}/create
Content-Type: application/json

### STORE
POST {{api}}/store
Content-Type: application/json

{
    "account": 1,
    "amount": 20
}
